<?php
declare(strict_types=1);

// TangocardAuth SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

TangocardAuthUtility::setRegistrar(function (TangocardAuthUtility $u): void {
    $u->clean = [TangocardAuthClean::class, 'call'];
    $u->done = [TangocardAuthDone::class, 'call'];
    $u->make_error = [TangocardAuthMakeError::class, 'call'];
    $u->feature_add = [TangocardAuthFeatureAdd::class, 'call'];
    $u->feature_hook = [TangocardAuthFeatureHook::class, 'call'];
    $u->feature_init = [TangocardAuthFeatureInit::class, 'call'];
    $u->fetcher = [TangocardAuthFetcher::class, 'call'];
    $u->make_fetch_def = [TangocardAuthMakeFetchDef::class, 'call'];
    $u->make_context = [TangocardAuthMakeContext::class, 'call'];
    $u->make_options = [TangocardAuthMakeOptions::class, 'call'];
    $u->make_request = [TangocardAuthMakeRequest::class, 'call'];
    $u->make_response = [TangocardAuthMakeResponse::class, 'call'];
    $u->make_result = [TangocardAuthMakeResult::class, 'call'];
    $u->make_point = [TangocardAuthMakePoint::class, 'call'];
    $u->make_spec = [TangocardAuthMakeSpec::class, 'call'];
    $u->make_url = [TangocardAuthMakeUrl::class, 'call'];
    $u->param = [TangocardAuthParam::class, 'call'];
    $u->prepare_auth = [TangocardAuthPrepareAuth::class, 'call'];
    $u->prepare_body = [TangocardAuthPrepareBody::class, 'call'];
    $u->prepare_headers = [TangocardAuthPrepareHeaders::class, 'call'];
    $u->prepare_method = [TangocardAuthPrepareMethod::class, 'call'];
    $u->prepare_params = [TangocardAuthPrepareParams::class, 'call'];
    $u->prepare_path = [TangocardAuthPreparePath::class, 'call'];
    $u->prepare_query = [TangocardAuthPrepareQuery::class, 'call'];
    $u->graphql_body = [TangocardAuthGraphql::class, 'body'];
    $u->graphql_errors = [TangocardAuthGraphql::class, 'errors'];
    $u->result_basic = [TangocardAuthResultBasic::class, 'call'];
    $u->result_body = [TangocardAuthResultBody::class, 'call'];
    $u->result_headers = [TangocardAuthResultHeaders::class, 'call'];
    $u->transform_request = [TangocardAuthTransformRequest::class, 'call'];
    $u->transform_response = [TangocardAuthTransformResponse::class, 'call'];
});
